name = "artist"
description = "A elegant theme for artists and musicians"
license = "MIT"
homepage = "https://github.com/pooletergeist/artist-zola-theme"
min_version = "0.17.0"
demo = "example-site-oscar.pages.dev"


[extra]

